// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGd76iVavpA7BeRHPkz13-t2bZplu7KnI',
    appId: '1:462898727054:web:0be8c0008e84ee836ee1df',
    messagingSenderId: '462898727054',
    projectId: 'teste-61172',
    authDomain: 'teste-61172.firebaseapp.com',
    storageBucket: 'teste-61172.firebasestorage.app',
    measurementId: 'G-JDDHBZRQYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyx0NxuRCpTxLxokQvGU4vH2hqYtg9Ts',
    appId: '1:462898727054:android:fb304532d4841f0e6ee1df',
    messagingSenderId: '462898727054',
    projectId: 'teste-61172',
    storageBucket: 'teste-61172.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvwL7yq9wgWdoKF-g3cVCUjqFkcpcDQ6w',
    appId: '1:462898727054:ios:401ed3cf1c26f7e86ee1df',
    messagingSenderId: '462898727054',
    projectId: 'teste-61172',
    storageBucket: 'teste-61172.firebasestorage.app',
    iosBundleId: 'com.example.gf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvwL7yq9wgWdoKF-g3cVCUjqFkcpcDQ6w',
    appId: '1:462898727054:ios:401ed3cf1c26f7e86ee1df',
    messagingSenderId: '462898727054',
    projectId: 'teste-61172',
    storageBucket: 'teste-61172.firebasestorage.app',
    iosBundleId: 'com.example.gf',
  );
}
