// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDpszUxn4NDDJv6756rZIPiSrsWxCqa0',
    appId: '1:535611524508:web:7dde156684f34817d87459',
    messagingSenderId: '535611524508',
    projectId: 'gerencie-b058a',
    authDomain: 'gerencie-b058a.firebaseapp.com',
    storageBucket: 'gerencie-b058a.appspot.com',
    measurementId: 'G-V6C4JX8XDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxAJjFl9GqMfUeqyB_ojgWsW0Eocv4Jwc',
    appId: '1:535611524508:android:1325a60ccd17034ad87459',
    messagingSenderId: '535611524508',
    projectId: 'gerencie-b058a',
    storageBucket: 'gerencie-b058a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJgi-zWmSDTN0inqoXBnkzg-ZgJtjUyw',
    appId: '1:535611524508:ios:a1131110c94802fcd87459',
    messagingSenderId: '535611524508',
    projectId: 'gerencie-b058a',
    storageBucket: 'gerencie-b058a.appspot.com',
    iosBundleId: 'com.example.gf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaJgi-zWmSDTN0inqoXBnkzg-ZgJtjUyw',
    appId: '1:535611524508:ios:a1131110c94802fcd87459',
    messagingSenderId: '535611524508',
    projectId: 'gerencie-b058a',
    storageBucket: 'gerencie-b058a.appspot.com',
    iosBundleId: 'com.example.gf',
  );
}
